[02-Sep-2024 07:54:35 UTC] PHP Fatal error:  Uncaught Error: Class "_ContaoManager\Contao\ManagerApi\HttpKernel\ApiProblemResponse" not found in phar:///var/www/hrm/public/contao-manager.phar.php/dist/api.php:24
Stack trace:
#0 /var/www/hrm/public/contao-manager.phar.php(88): Phar::webPhar(NULL, 'index.html', NULL, Array, 'rewrites')
#1 {main}
  thrown in phar:///var/www/hrm/public/contao-manager.phar.php/dist/api.php on line 24
[02-Sep-2024 07:54:35 UTC] PHP Fatal error:  Uncaught Error: Class "_ContaoManager\Symfony\Component\ErrorHandler\Error\FatalError" not found in phar:///var/www/hrm/public/contao-manager.phar.php/vendor/symfony/error-handler/ErrorHandler.php:592
Stack trace:
#0 [internal function]: _ContaoManager\Symfony\Component\ErrorHandler\ErrorHandler::handleFatalError()
#1 {main}
  thrown in phar:///var/www/hrm/public/contao-manager.phar.php/vendor/symfony/error-handler/ErrorHandler.php on line 592
[02-Sep-2024 07:57:14 UTC] [2024-09-02T07:57:13.082091+00:00] request.INFO: Matched route "contao_managerapi_server_adminuser__invoke". {"route":"contao_managerapi_server_adminuser__invoke","route_parameters":{"_route":"contao_managerapi_server_adminuser__invoke","_controller":"_ContaoManager\\Contao\\ManagerApi\\Controller\\Server\\AdminUserController"},"request_uri":"https://hrm.loc/contao-manager.phar.php/api/server/admin-user","method":"GET"} []
[02-Sep-2024 07:57:14 UTC] [2024-09-02T07:57:13.086791+00:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"api","authenticators":4} []
[02-Sep-2024 07:57:14 UTC] [2024-09-02T07:57:13.087476+00:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\LoginAuthenticator"} []
[02-Sep-2024 07:57:14 UTC] [2024-09-02T07:57:13.087514+00:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\LoginAuthenticator"} []
[02-Sep-2024 07:57:14 UTC] [2024-09-02T07:57:13.087658+00:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\PasswordlessAuthenticator"} []
[02-Sep-2024 07:57:14 UTC] [2024-09-02T07:57:13.087682+00:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\PasswordlessAuthenticator"} []
[02-Sep-2024 07:57:14 UTC] [2024-09-02T07:57:13.087684+00:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[02-Sep-2024 07:57:14 UTC] [2024-09-02T07:57:13.088262+00:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[02-Sep-2024 07:57:14 UTC] [2024-09-02T07:57:13.088275+00:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[02-Sep-2024 07:57:14 UTC] [2024-09-02T07:57:13.088285+00:00] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[02-Sep-2024 07:57:14 UTC] [2024-09-02T07:57:13.088715+00:00] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[02-Sep-2024 07:57:14 UTC] [2024-09-02T07:57:13.089978+00:00] security.INFO: Guard authentication successful! {"token":{"_ContaoManager\\Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken":"PostAuthenticationGuardToken(user=\"sarwar\", authenticated=true, roles=\"ROLE_ADMIN\")"},"authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[02-Sep-2024 07:57:14 UTC] [2024-09-02T07:57:13.090084+00:00] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[02-Sep-2024 07:57:14 UTC] [2024-09-02T07:57:13.090088+00:00] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[02-Sep-2024 07:57:14 UTC] [2024-09-02T07:57:14.046862+00:00] app.CRITICAL: Uncaught PHP Exception _ContaoManager\Symfony\Component\Process\Exception\ProcessFailedException: "The command "'/usr/local/bin/php' '-q' '-dmax_execution_time=0' '-dmemory_limit=-1' '-ddisplay_errors=0' '-ddisplay_startup_errors=0' '-derror_reporting=0' '-dallow_url_fopen=1' '-ddisable_functions=' '-ddate.timezone=UTC' '/var/www/hrm/vendor/contao/manager-bundle/bin/contao-console' 'contao:user:list' '--format=json' '--column=username' '--column=name' '--column=admin' '--column=dateAdded' '--column=lastLogin' '--no-interaction'" failed.  Exit Code: 255(Unknown error)  Working directory: /var/www/hrm  Output: ================   Error Output: ================ 07:57:14 CRITICAL  [console] Error thrown while running command "contao:user:list --format=json --column=username --column=name --column=admin --column=dateAdded --column=lastLogin --no-interaction". Message: "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hrm.tl_user' doesn't exist" ["exception" => Doctrine\DBAL\Exception\TableNotFoundException { …},"command" => "contao:user:list --format=json --column=username --column=name --column=admin --column=dateAdded --column=lastLogin --no-interaction","message" => "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hrm.tl_user' doesn't exist"]  In ExceptionConverter.php line 49:                                                                                   An exception occurred while executing a query: SQLSTATE[42S02]: Base table      or view not found: 1146 Table 'hrm.tl_user' doesn't exist                                                                                                      In Exception.php line 28:                                                                                   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hrm.tl_user' doe     sn't exist                                                                                                                                                     In Connection.php line 71:                                                                                   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hrm.tl_user' doe     sn't exist                                                                                                                                                     contao:user:list [--column COLUMN] [--admins] [--format FORMAT]  " at phar:///var/www/hrm/public/contao-manager.phar.php/api/Process/ContaoConsole.php line 162 {"exception":"[object] (_ContaoManager\\Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"'/usr/local/bin/php' '-q' '-dmax_execution_time=0' '-dmemory_limit=-1' '-ddisplay_errors=0' '-ddisplay_startup_errors=0' '-derror_reporting=0' '-dallow_url_fopen=1' '-ddisable_functions=' '-ddate.timezone=UTC' '/var/www/hrm/vendor/contao/manager-bundle/bin/contao-console' 'contao:user:list' '--format=json' '--column=username' '--column=name' '--column=admin' '--column=dateAdded' '--column=lastLogin' '--no-interaction'\" failed.\n\nExit Code: 255(Unknown error)\n\nWorking directory: /var/www/hrm\n\nOutput:\n================\n\n\nError Output:\n================\n07:57:14 CRITICAL  [console] Error thrown while running command \"contao:user:list --format=json --column=username --column=name --column=admin --column=dateAdded --column=lastLogin --no-interaction\". Message: \"An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hrm.tl_user' doesn't exist\" [\"exception\" => Doctrine\\DBAL\\Exception\\TableNotFoundException { …},\"command\" => \"contao:user:list --format=json --column=username --column=name --column=admin --column=dateAdded --column=lastLogin --no-interaction\",\"message\" => \"An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hrm.tl_user' doesn't exist\"]\n\nIn ExceptionConverter.php line 49:\n                                                                               \n  An exception occurred while executing a query: SQLSTATE[42S02]: Base table   \n  or view not found: 1146 Table 'hrm.tl_user' doesn't exist                    \n                                                                               \n\nIn Exception.php line 28:\n                                                                               \n  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hrm.tl_user' doe  \n  sn't exist                                                                   \n                                                                               \n\nIn Connection.php line 71:\n                                                                               \n  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hrm.tl_user' doe  \n  sn't exist                                                                   \n                                                                               \n\ncontao:user:list [--column COLUMN] [--admins] [--format FORMAT]\n\n at phar:///var/www/hrm/public/contao-manager.phar.php/api/Process/ContaoConsole.php:162)"} []
